/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as FarmerBookRouteImport } from './routes/farmer.book'
import { Route as FarmerDashboardRouteImport } from './routes/farmer.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/farmer/',
  path: '/farmer/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerBookRoute = FarmerBookRouteImport.update({
  id: '/farmer/book',
  path: '/farmer/book',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerDashboardRoute = FarmerDashboardRouteImport.update({
  id: '/farmer/dashboard',
  path: '/farmer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer': typeof FarmerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer/book': typeof FarmerBookRoute
  '/farmer/dashboard': typeof FarmerDashboardRoute
  '/farmer/': typeof FarmerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/farmer/book' | '/farmer/dashboard' | '/farmer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/farmer/book' | '/farmer/dashboard' | '/farmer'
  id: '__root__' | '/' | '/farmer/book' | '/farmer/dashboard' | '/farmer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerBookRoute: typeof FarmerBookRoute
  FarmerDashboardRoute: typeof FarmerDashboardRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/farmer'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/book': {
      id: '/farmer/book'
      path: '/farmer/book'
      fullPath: '/farmer/book'
      preLoaderRoute: typeof FarmerBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/dashboard': {
      id: '/farmer/dashboard'
      path: '/farmer/dashboard'
      fullPath: '/farmer/dashboard'
      preLoaderRoute: typeof FarmerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerBookRoute: FarmerBookRoute,
  FarmerDashboardRoute: FarmerDashboardRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
